### ISSUE TITLE
Add release notes to the openQASM Project

### ISSUE THREAD

**Issue by taalexander** [openqasm/openqasm#328]
### What is the expected enhancement?

The openQASM project should have release notes associated with each tagged release (see #321). These should contain a summary of all changes included in the prepared release (or the development branch). For ease (and distribution) of maintenance, we should consider using [reno](https://docs.openstack.org/reno/latest/) which has been used with success in Qiskit Terra [1](https://github.com/Qiskit/qiskit-terra#changelog-and-release-notes), [2](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#release-notes).

**Comment by levbishop** [comment]
I agree we should definitely keep release notes and use a tool that allows tracking the release notes along with the corresponding PRs. I'm pretty happy with reno to be that, although the terra usage is a slight mismatch with how reno is intended to be used as far as maintaining multiple branches of development (to the extent that you are just doing straight-line development and cutting releases every so often its easy, otherwise you'd ideally generate release notes separately for each stable branch, whereas for terra we end up with something in between that isn't perfectly well supported).
